package configuration for libffi is not found
have_header: checking for ffi.h... -------------------- no

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'      -lruby-static  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main() {return 0;}
/* end */

"/usr/local/bin/gcc-4.2 -E -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe  conftest.c -o conftest.i"
conftest.c:3:17: error: ffi.h: No such file or directory
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ffi.h>
/* end */

--------------------

find_header: checking for ffi.h in /usr/local/include,/usr/include/ffi... -------------------- yes

"/usr/local/bin/gcc-4.2 -E -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe  conftest.c -o conftest.i"
conftest.c:3:17: error: ffi.h: No such file or directory
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ffi.h>
/* end */

"/usr/local/bin/gcc-4.2 -E -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe -I/usr/local/include conftest.c -o conftest.i"
conftest.c:3:17: error: ffi.h: No such file or directory
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ffi.h>
/* end */

"/usr/local/bin/gcc-4.2 -E -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe -I/usr/include/ffi conftest.c -o conftest.i"
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ffi.h>
/* end */

--------------------

have_library: checking for ffi_call() in -lffi... -------------------- yes

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'      -lruby-static -lffi  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <ffi.h>
4: 
5: /*top*/
6: int main() {return 0;}
7: int t() { void ((*volatile p)()); p = (void ((*)()))ffi_call; return 0; }
/* end */

--------------------

have_func: checking for ffi_prep_closure()... -------------------- yes

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
conftest.c: In function ‘t’:
conftest.c:5: error: ‘ffi_prep_closure’ undeclared (first use in this function)
conftest.c:5: error: (Each undeclared identifier is reported only once
conftest.c:5: error: for each function it appears in.)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { void ((*volatile p)()); p = (void ((*)()))ffi_prep_closure; return 0; }
/* end */

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { ffi_prep_closure(); return 0; }
/* end */

--------------------

have_func: checking for ffi_raw_call()... -------------------- no

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
conftest.c: In function ‘t’:
conftest.c:5: error: ‘ffi_raw_call’ undeclared (first use in this function)
conftest.c:5: error: (Each undeclared identifier is reported only once
conftest.c:5: error: for each function it appears in.)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { void ((*volatile p)()); p = (void ((*)()))ffi_raw_call; return 0; }
/* end */

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
Undefined symbols for architecture x86_64:
  "_ffi_raw_call", referenced from:
      _t in ccNAXgoB.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { ffi_raw_call(); return 0; }
/* end */

--------------------

have_func: checking for rb_thread_blocking_region()... -------------------- yes

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { void ((*volatile p)()); p = (void ((*)()))rb_thread_blocking_region; return 0; }
/* end */

--------------------

have_func: checking for rb_thread_call_with_gvl()... -------------------- yes

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
conftest.c: In function ‘t’:
conftest.c:5: error: ‘rb_thread_call_with_gvl’ undeclared (first use in this function)
conftest.c:5: error: (Each undeclared identifier is reported only once
conftest.c:5: error: for each function it appears in.)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_with_gvl; return 0; }
/* end */

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { rb_thread_call_with_gvl(); return 0; }
/* end */

--------------------

have_func: checking for rb_thread_call_without_gvl()... -------------------- yes

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
conftest.c: In function ‘t’:
conftest.c:5: error: ‘rb_thread_call_without_gvl’ undeclared (first use in this function)
conftest.c:5: error: (Each undeclared identifier is reported only once
conftest.c:5: error: for each function it appears in.)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { void ((*volatile p)()); p = (void ((*)()))rb_thread_call_without_gvl; return 0; }
/* end */

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { rb_thread_call_without_gvl(); return 0; }
/* end */

--------------------

have_func: checking for ffi_prep_cif_var()... -------------------- no

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
conftest.c: In function ‘t’:
conftest.c:5: error: ‘ffi_prep_cif_var’ undeclared (first use in this function)
conftest.c:5: error: (Each undeclared identifier is reported only once
conftest.c:5: error: for each function it appears in.)
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { void ((*volatile p)()); p = (void ((*)()))ffi_prep_cif_var; return 0; }
/* end */

"/usr/local/bin/gcc-4.2 -o conftest -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/x86_64-darwin12.3.0 -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1/ruby/backward -I/home/dmccarth/.rbenv/versions/1.9.2-p180/include/ruby-1.9.1 -I. -I/usr/include/ffi -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'  -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE  -I'/home/dmccarth/.rbenv/versions/1.9.2-p180/include'   -O3 -Wno-error=shorten-64-to-32  -pipe conftest.c  -L. -L/home/dmccarth/.rbenv/versions/1.9.2-p180/lib -L. -L'/home/dmccarth/.rbenv/versions/1.9.2-p180/lib'     -lffi  -lruby-static -lffi  -lpthread -ldl -lobjc "
Undefined symbols for architecture x86_64:
  "_ffi_prep_cif_var", referenced from:
      _t in ccHnRE7L.o
ld: symbol(s) not found for architecture x86_64
collect2: ld returned 1 exit status
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: /*top*/
4: int main() {return 0;}
5: int t() { ffi_prep_cif_var(); return 0; }
/* end */

--------------------

